# Generated by Django 3.2.3 on 2021-06-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210627_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='on_moderation',
        ),
    ]
